# Generated by Django 3.2.5 on 2021-07-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210714_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sport'),
        ),
    ]
