# Generated by Django 3.2.5 on 2021-07-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'tournament')},
        ),
    ]
