# Generated by Django 3.2.5 on 2021-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211006_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='fisrtname',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(default='bb', max_length=30),
            preserve_default=False,
        ),
    ]
