# Generated by Django 3.2.5 on 2021-10-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211006_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fisrtname',
            new_name='firstname',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('firstname', 'lastname')},
        ),
    ]
