# Generated by Django 3.2.5 on 2021-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament', 'round']},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round', 'player1', 'player2')},
        ),
    ]
