# Generated by Django 3.2.5 on 2021-10-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211017_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='points1',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='points2',
            new_name='score2',
        ),
    ]
