# Generated by Django 3.2.8 on 2021-11-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211018_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['sport', 'name']},
        ),
    ]
